name: Deploy PyMOL Plugin

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      # Step 1: Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          environment-file: etc/environment.yml
          auto-activate-base: true
          auto-update-conda: true
          python-version: 3.12
      - run: |
          conda info
          conda list

      # Step 6: Package the plugin
      - name: Package the Plugin
        run: |
          mkdir -p dist
          zip -r dist.zip src
          cp dist.zip dist/

      # Step 7: Deploy to GitHub Releases
      - name: Deploy to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/*
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.run_number }}
          name: DNASeq Kinase Analyzer Plugin Release
          prerelease: false
