name: Deploy PyMOL Plugin

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      # Step 1: Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          environment-file: etc/environment.yml
          auto-activate-base: true
          auto-update-conda: true
          python-version: 3.12
      - run: |
          conda info
          conda list

      # Step 4: Install setuptools and wheel (if not already installed)
      - name: Install Build Tools
        run: |
          conda install -c conda-forge setuptools wheel

      # Step 5: Create the .tar.gz package
      - name: Build Source Distribution
        run: |
          python etc/setup.py sdist

      # Step 6: Deploy to GitHub Releases
      - name: Deploy to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/*.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.run_number }}
          name: DNASeq Kinase Analyzer Plugin Release
          prerelease: false
